######## Frontend(Next.js) ########
FROM node:23.7-bookworm-slim AS base
WORKDIR /usr/src/nextjs

# Install dependencies into a temp directory to leverage caching
FROM base AS install
RUN mkdir -p /temp/dev
COPY package*.json /temp/dev/
RUN cd /temp/dev && npm ci --include=dev

# Copy node_modules from temp directory, then copy the rest of the project
FROM base AS dev
COPY --from=install /temp/dev/node_modules ./node_modules
COPY . .

# Expose the port and start the Next.js development server
EXPOSE 3000
CMD ["npm", "run", "dev"]
